In [20]:
import numpy as np
import pandas as pd
import seaborn as sns

In [4]:
data = pd.read_excel("C:/Users/htcso/OneDrive/Masaüstü/pythonProject/datasets/D1.xlsx")
data.head()

D1
0  785
1  583
2  377
3  723
4  698

## Min-Max Scaling
Değerler verilen min-max aralığa dönüştürülür. (default 0 ve 1 arasında)
Aykırı gözlemlerden etkilenir.

In [5]:
from sklearn import preprocessing as pr

In [16]:
min_max = pr.MinMaxScaler().fit_transform(data)
min_max

array([[0.80182232],
       [0.57175399],
       [0.33712984],
       [0.73120729],
       [0.70273349],
       [0.36560364],
       [0.83826879],
       [0.54328018],
       [0.15148064],
       [0.89179954],
       [1.        ],
       [0.83485194],
       [0.10933941],
       [0.08428246],
       [0.77334852],
       [0.54328018],
       [0.75284738],
       [0.99202733],
       [0.61958998],
       [0.8690205 ],
       [0.33712984],
       [0.29840547],
       [0.87357631],
       [0.88268793],
       [0.64350797],
       [0.        ],
       [0.92482916],
       [0.60022779],
       [0.58656036],
       [0.85990888]])

In [17]:
data2 = pd.DataFrame(min_max)
data2.head()

0
0  0.801822
1  0.571754
2  0.337130
3  0.731207
4  0.702733

## Robust Scaling
Aykırı gözlemlerden daha az etkilenir.

In [18]:
robust = pr.RobustScaler().fit_transform(data)
robust

array([[ 0.28955798],
       [-0.22805894],
       [-0.75592569],
       [ 0.13068546],
       [ 0.06662396],
       [-0.69186419],
       [ 0.37155669],
       [-0.29212044],
       [-1.17360666],
       [ 0.49199231],
       [ 0.73542601],
       [ 0.36386931],
       [-1.26841768],
       [-1.3247918 ],
       [ 0.22549648],
       [-0.29212044],
       [ 0.1793722 ],
       [ 0.71748879],
       [-0.12043562],
       [ 0.44074311],
       [-0.75592569],
       [-0.84304933],
       [ 0.45099295],
       [ 0.47149263],
       [-0.06662396],
       [-1.51441384],
       [ 0.56630365],
       [-0.16399744],
       [-0.19474696],
       [ 0.42024343]])

## Standart Scaler
Standart normal dağılım

In [19]:
ss = pr.StandardScaler().fit_transform(data)
ss

array([[ 0.65418557],
       [-0.16169518],
       [-0.99373198],
       [ 0.40376673],
       [ 0.30279139],
       [-0.89275664],
       [ 0.78343401],
       [-0.26267052],
       [-1.6520912 ],
       [ 0.97326765],
       [ 1.35697394],
       [ 0.77131697],
       [-1.8015347 ],
       [-1.890393  ],
       [ 0.55321023],
       [-0.26267052],
       [ 0.48050799],
       [ 1.32870084],
       [ 0.00794339],
       [ 0.89248737],
       [-0.99373198],
       [-1.13105844],
       [ 0.90864343],
       [ 0.94095554],
       [ 0.09276268],
       [-2.18928001],
       [ 1.09039904],
       [-0.06071984],
       [-0.109188  ],
       [ 0.86017526]])

# Kategorik Değişken Kodlama

In [21]:
titanic = sns.load_dataset("titanic")
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

## İki sınıflı için Label Encoder

In [23]:
binary_sex = pr.LabelEncoder().fit_transform(titanic["sex"])
binary_sex[:10]

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0])

In [24]:
titanic["sex_code"] = binary

In [25]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  sex_code  
0    man        True  NaN  Southampton    no  False         1  
1  woman       False    C    Cherbourg   yes  False         0  
2  woman       False  NaN  Southampton   yes   True         0  
3  woman       False    C  Southampton   yes  False         0  
4    man        True  NaN  Southampton    no   True         1

In [26]:
titanic[["sex", "sex_code"]].head()

sex  sex_code
0    male         1
1  female         0
2  female         0
3  female         0
4    male         1

## İkiden fazla sınıf için LabelEncoder
LabelEncoder ikiden fazla sınıf için, sınıflar arasında hiyerarşi var olduğunu kabul eder. Problem ortaya çıkartır.

In [27]:
tips = sns.load_dataset("tips")
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [29]:
tips["day_code"] = pr.LabelEncoder().fit_transform(tips["day"])
tips.head()

total_bill   tip     sex smoker  day    time  size  day_code
0       16.99  1.01  Female     No  Sun  Dinner     2         2
1       10.34  1.66    Male     No  Sun  Dinner     3         2
2       21.01  3.50    Male     No  Sun  Dinner     3         2
3       23.68  3.31    Male     No  Sun  Dinner     2         2
4       24.59  3.61  Female     No  Sun  Dinner     4         2

## İkiden fazla sınıf için One Hot Encoding
Hiyerarşinin olmadığı değişkenlerde

In [42]:
df = pd.read_excel("C:/Users/htcso/OneDrive/Masaüstü/pythonProject/datasets/kategorik.xlsx")
df2 = df.copy()
df2.head()
# Eğitim değişkeni hiyerarşik

Cinsiyet AraçRenk      Eğitim
0    Kadın    Yeşil  Üniversite
1    Erkek     Mavi     Doktora
2    Kadın  Kırmızı     Doktora
3    Erkek    Beyaz  Üniversite
4    Kadın  Kırmızı  Üniversite

In [39]:
onehot = pd.get_dummies(df2, columns=["Cinsiyet", "AraçRenk"], drop_first = True)
onehot.head()

Eğitim  Cinsiyet_Kadın  AraçRenk_Kırmızı  AraçRenk_Mavi  \
0  Üniversite               1                 0              0   
1     Doktora               0                 0              1   
2     Doktora               1                 1              0   
3  Üniversite               0                 0              0   
4  Üniversite               1                 1              0   

   AraçRenk_Siyah  AraçRenk_Yeşil  
0               0               1  
1               0               0  
2               0               0  
3               0               0  
4               0               0

## Hiyerarşiyi Doğru Sırayla Belirtmek

In [40]:
df2.head()

Cinsiyet AraçRenk      Eğitim
0    Kadın    Yeşil  Üniversite
1    Erkek     Mavi     Doktora
2    Kadın  Kırmızı     Doktora
3    Erkek    Beyaz  Üniversite
4    Kadın  Kırmızı  Üniversite

In [43]:
sıralı = pd.Categorical(df2["Eğitim"], 
                        categories = ["İlkokul", "Lise", "Üniversite", "Yüksek Lisans", "Doktora"],
                        ordered = True)

df2["eğitim_kod"], sıra = pd.factorize(sıralı, sort=True)

df2.head()

Cinsiyet AraçRenk      Eğitim  eğitim_kod
0    Kadın    Yeşil  Üniversite           2
1    Erkek     Mavi     Doktora           4
2    Kadın  Kırmızı     Doktora           4
3    Erkek    Beyaz  Üniversite           2
4    Kadın  Kırmızı  Üniversite           2